/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from "./mocks";
export type { mocks };
export type { OnlyHoldFactory } from "./OnlyHoldFactory";
export type { OnlyHoldNFT } from "./OnlyHoldNFT";
export type { OnlyHoldSubscription } from "./OnlyHoldSubscription";
