/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace OnlyHoldFactory {
  export type NFTParamsStruct = {
    enable: boolean;
    name: string;
    symbol: string;
    mintPrice: BigNumberish;
    maxSupply: BigNumberish;
    baseURI: string;
  };

  export type NFTParamsStructOutput = [
    enable: boolean,
    name: string,
    symbol: string,
    mintPrice: bigint,
    maxSupply: bigint,
    baseURI: string
  ] & {
    enable: boolean;
    name: string;
    symbol: string;
    mintPrice: bigint;
    maxSupply: bigint;
    baseURI: string;
  };

  export type SubParamsStruct = {
    enable: boolean;
    monthlyPrice: BigNumberish;
    customStablecoin: AddressLike;
  };

  export type SubParamsStructOutput = [
    enable: boolean,
    monthlyPrice: bigint,
    customStablecoin: string
  ] & { enable: boolean; monthlyPrice: bigint; customStablecoin: string };
}

export interface OnlyHoldFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allCreators"
      | "blacklist"
      | "blacklisted"
      | "checkAccess"
      | "creatorAt"
      | "creatorCount"
      | "creatorProfiles"
      | "deactivateCreator"
      | "defaultStablecoin"
      | "defaultStablecoinDecimals"
      | "isRegistered"
      | "launchCreator"
      | "owner"
      | "renounceOwnership"
      | "resolveUsername"
      | "setDefaultStablecoin"
      | "setTreasury"
      | "transferOwnership"
      | "treasury"
      | "usernameToAddress"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CreatorDeactivated"
      | "CreatorLaunched"
      | "DefaultStablecoinUpdated"
      | "OwnershipTransferred"
      | "TreasuryUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allCreators",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "blacklist",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkAccess",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "creatorProfiles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateCreator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultStablecoin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defaultStablecoinDecimals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "launchCreator",
    values: [
      string,
      string,
      OnlyHoldFactory.NFTParamsStruct,
      OnlyHoldFactory.SubParamsStruct
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveUsername",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultStablecoin",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "usernameToAddress",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "allCreators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "blacklist", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "blacklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "creatorAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "creatorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorProfiles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultStablecoin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultStablecoinDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "launchCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveUsername",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultStablecoin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "usernameToAddress",
    data: BytesLike
  ): Result;
}

export namespace CreatorDeactivatedEvent {
  export type InputTuple = [creator: AddressLike];
  export type OutputTuple = [creator: string];
  export interface OutputObject {
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreatorLaunchedEvent {
  export type InputTuple = [
    creator: AddressLike,
    username: string,
    nftContract: AddressLike,
    subscriptionContract: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    username: string,
    nftContract: string,
    subscriptionContract: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    creator: string;
    username: string;
    nftContract: string;
    subscriptionContract: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultStablecoinUpdatedEvent {
  export type InputTuple = [newStablecoin: AddressLike];
  export type OutputTuple = [newStablecoin: string];
  export interface OutputObject {
    newStablecoin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
  export type OutputTuple = [oldTreasury: string, newTreasury: string];
  export interface OutputObject {
    oldTreasury: string;
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OnlyHoldFactory extends BaseContract {
  connect(runner?: ContractRunner | null): OnlyHoldFactory;
  waitForDeployment(): Promise<this>;

  interface: OnlyHoldFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allCreators: TypedContractMethod<[], [string[]], "view">;

  blacklist: TypedContractMethod<
    [account: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  blacklisted: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  checkAccess: TypedContractMethod<
    [creatorAddress: AddressLike, fan: AddressLike],
    [[boolean, string] & { hasAccess: boolean; via: string }],
    "view"
  >;

  creatorAt: TypedContractMethod<[index: BigNumberish], [string], "view">;

  creatorCount: TypedContractMethod<[], [bigint], "view">;

  creatorProfiles: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, string, bigint, boolean] & {
        creatorAddress: string;
        nftContract: string;
        subscriptionContract: string;
        username: string;
        metadataURI: string;
        registeredAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  deactivateCreator: TypedContractMethod<
    [creatorAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  defaultStablecoin: TypedContractMethod<[], [string], "view">;

  defaultStablecoinDecimals: TypedContractMethod<[], [bigint], "view">;

  isRegistered: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  launchCreator: TypedContractMethod<
    [
      username: string,
      metadataURI: string,
      nft: OnlyHoldFactory.NFTParamsStruct,
      sub: OnlyHoldFactory.SubParamsStruct
    ],
    [[string, string] & { nftContract: string; subContract: string }],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveUsername: TypedContractMethod<
    [username: string],
    [[string, string, string] & { creator: string; nft: string; sub: string }],
    "view"
  >;

  setDefaultStablecoin: TypedContractMethod<
    [newStablecoin: AddressLike, decimals: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  usernameToAddress: TypedContractMethod<[arg0: string], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allCreators"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "blacklist"
  ): TypedContractMethod<
    [account: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "blacklisted"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "checkAccess"
  ): TypedContractMethod<
    [creatorAddress: AddressLike, fan: AddressLike],
    [[boolean, string] & { hasAccess: boolean; via: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "creatorAt"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "creatorCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "creatorProfiles"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, string, bigint, boolean] & {
        creatorAddress: string;
        nftContract: string;
        subscriptionContract: string;
        username: string;
        metadataURI: string;
        registeredAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deactivateCreator"
  ): TypedContractMethod<[creatorAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "defaultStablecoin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "defaultStablecoinDecimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "launchCreator"
  ): TypedContractMethod<
    [
      username: string,
      metadataURI: string,
      nft: OnlyHoldFactory.NFTParamsStruct,
      sub: OnlyHoldFactory.SubParamsStruct
    ],
    [[string, string] & { nftContract: string; subContract: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveUsername"
  ): TypedContractMethod<
    [username: string],
    [[string, string, string] & { creator: string; nft: string; sub: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "setDefaultStablecoin"
  ): TypedContractMethod<
    [newStablecoin: AddressLike, decimals: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usernameToAddress"
  ): TypedContractMethod<[arg0: string], [string], "view">;

  getEvent(
    key: "CreatorDeactivated"
  ): TypedContractEvent<
    CreatorDeactivatedEvent.InputTuple,
    CreatorDeactivatedEvent.OutputTuple,
    CreatorDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "CreatorLaunched"
  ): TypedContractEvent<
    CreatorLaunchedEvent.InputTuple,
    CreatorLaunchedEvent.OutputTuple,
    CreatorLaunchedEvent.OutputObject
  >;
  getEvent(
    key: "DefaultStablecoinUpdated"
  ): TypedContractEvent<
    DefaultStablecoinUpdatedEvent.InputTuple,
    DefaultStablecoinUpdatedEvent.OutputTuple,
    DefaultStablecoinUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;

  filters: {
    "CreatorDeactivated(address)": TypedContractEvent<
      CreatorDeactivatedEvent.InputTuple,
      CreatorDeactivatedEvent.OutputTuple,
      CreatorDeactivatedEvent.OutputObject
    >;
    CreatorDeactivated: TypedContractEvent<
      CreatorDeactivatedEvent.InputTuple,
      CreatorDeactivatedEvent.OutputTuple,
      CreatorDeactivatedEvent.OutputObject
    >;

    "CreatorLaunched(address,string,address,address,uint256)": TypedContractEvent<
      CreatorLaunchedEvent.InputTuple,
      CreatorLaunchedEvent.OutputTuple,
      CreatorLaunchedEvent.OutputObject
    >;
    CreatorLaunched: TypedContractEvent<
      CreatorLaunchedEvent.InputTuple,
      CreatorLaunchedEvent.OutputTuple,
      CreatorLaunchedEvent.OutputObject
    >;

    "DefaultStablecoinUpdated(address)": TypedContractEvent<
      DefaultStablecoinUpdatedEvent.InputTuple,
      DefaultStablecoinUpdatedEvent.OutputTuple,
      DefaultStablecoinUpdatedEvent.OutputObject
    >;
    DefaultStablecoinUpdated: TypedContractEvent<
      DefaultStablecoinUpdatedEvent.InputTuple,
      DefaultStablecoinUpdatedEvent.OutputTuple,
      DefaultStablecoinUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TreasuryUpdated(address,address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
  };
}
