/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface OnlyHoldSubscriptionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MONTH_SECONDS"
      | "PLATFORM_FEE_BPS"
      | "activeSubscriberCount"
      | "creator"
      | "getSubscribers"
      | "getSubscription"
      | "isSubscribed"
      | "monthlyPrice"
      | "owner"
      | "pendingCreatorEarnings"
      | "pendingPlatformFee"
      | "renounceOwnership"
      | "setMonthlyPrice"
      | "stablecoin"
      | "stablecoinDecimals"
      | "subscribe"
      | "subscribers"
      | "transferOwnership"
      | "treasury"
      | "withdrawBalance"
      | "withdrawEarnings"
      | "withdrawPlatformFee"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BalanceWithdrawn"
      | "CreatorWithdrew"
      | "MonthlyPriceUpdated"
      | "OwnershipTransferred"
      | "PlatformFeeWithdrawn"
      | "Subscribed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MONTH_SECONDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeSubscriberCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "creator", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getSubscribers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscription",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSubscribed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "monthlyPrice",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingCreatorEarnings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingPlatformFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMonthlyPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stablecoin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stablecoinDecimals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "subscribe",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawEarnings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPlatformFee",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "MONTH_SECONDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeSubscriberCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "creator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSubscribers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSubscribed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "monthlyPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingCreatorEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMonthlyPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stablecoin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stablecoinDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "subscribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subscribers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPlatformFee",
    data: BytesLike
  ): Result;
}

export namespace BalanceWithdrawnEvent {
  export type InputTuple = [subscriber: AddressLike, amount: BigNumberish];
  export type OutputTuple = [subscriber: string, amount: bigint];
  export interface OutputObject {
    subscriber: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreatorWithdrewEvent {
  export type InputTuple = [creator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [creator: string, amount: bigint];
  export interface OutputObject {
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MonthlyPriceUpdatedEvent {
  export type InputTuple = [oldPrice: BigNumberish, newPrice: BigNumberish];
  export type OutputTuple = [oldPrice: bigint, newPrice: bigint];
  export interface OutputObject {
    oldPrice: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeWithdrawnEvent {
  export type InputTuple = [treasury: AddressLike, amount: BigNumberish];
  export type OutputTuple = [treasury: string, amount: bigint];
  export interface OutputObject {
    treasury: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscribedEvent {
  export type InputTuple = [
    subscriber: AddressLike,
    amount: BigNumberish,
    months: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    subscriber: string,
    amount: bigint,
    months: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    subscriber: string;
    amount: bigint;
    months: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OnlyHoldSubscription extends BaseContract {
  connect(runner?: ContractRunner | null): OnlyHoldSubscription;
  waitForDeployment(): Promise<this>;

  interface: OnlyHoldSubscriptionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MONTH_SECONDS: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  activeSubscriberCount: TypedContractMethod<[], [bigint], "view">;

  creator: TypedContractMethod<[], [string], "view">;

  getSubscribers: TypedContractMethod<[], [string[]], "view">;

  getSubscription: TypedContractMethod<
    [account: AddressLike],
    [
      [bigint, bigint, boolean, bigint] & {
        deposited: bigint;
        expiresAt: bigint;
        isActive: boolean;
        remainingSeconds: bigint;
      }
    ],
    "view"
  >;

  isSubscribed: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  monthlyPrice: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingCreatorEarnings: TypedContractMethod<[], [bigint], "view">;

  pendingPlatformFee: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setMonthlyPrice: TypedContractMethod<
    [newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  stablecoin: TypedContractMethod<[], [string], "view">;

  stablecoinDecimals: TypedContractMethod<[], [bigint], "view">;

  subscribe: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  subscribers: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        deposited: bigint;
        expiresAt: bigint;
        lastDeposit: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  withdrawBalance: TypedContractMethod<[], [void], "nonpayable">;

  withdrawEarnings: TypedContractMethod<[], [void], "nonpayable">;

  withdrawPlatformFee: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MONTH_SECONDS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "activeSubscriberCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "creator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getSubscribers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getSubscription"
  ): TypedContractMethod<
    [account: AddressLike],
    [
      [bigint, bigint, boolean, bigint] & {
        deposited: bigint;
        expiresAt: bigint;
        isActive: boolean;
        remainingSeconds: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isSubscribed"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "monthlyPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingCreatorEarnings"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingPlatformFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMonthlyPrice"
  ): TypedContractMethod<[newPrice: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stablecoin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "stablecoinDecimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "subscribe"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "subscribers"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        deposited: bigint;
        expiresAt: bigint;
        lastDeposit: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawBalance"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawEarnings"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawPlatformFee"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "BalanceWithdrawn"
  ): TypedContractEvent<
    BalanceWithdrawnEvent.InputTuple,
    BalanceWithdrawnEvent.OutputTuple,
    BalanceWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "CreatorWithdrew"
  ): TypedContractEvent<
    CreatorWithdrewEvent.InputTuple,
    CreatorWithdrewEvent.OutputTuple,
    CreatorWithdrewEvent.OutputObject
  >;
  getEvent(
    key: "MonthlyPriceUpdated"
  ): TypedContractEvent<
    MonthlyPriceUpdatedEvent.InputTuple,
    MonthlyPriceUpdatedEvent.OutputTuple,
    MonthlyPriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeWithdrawn"
  ): TypedContractEvent<
    PlatformFeeWithdrawnEvent.InputTuple,
    PlatformFeeWithdrawnEvent.OutputTuple,
    PlatformFeeWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "Subscribed"
  ): TypedContractEvent<
    SubscribedEvent.InputTuple,
    SubscribedEvent.OutputTuple,
    SubscribedEvent.OutputObject
  >;

  filters: {
    "BalanceWithdrawn(address,uint256)": TypedContractEvent<
      BalanceWithdrawnEvent.InputTuple,
      BalanceWithdrawnEvent.OutputTuple,
      BalanceWithdrawnEvent.OutputObject
    >;
    BalanceWithdrawn: TypedContractEvent<
      BalanceWithdrawnEvent.InputTuple,
      BalanceWithdrawnEvent.OutputTuple,
      BalanceWithdrawnEvent.OutputObject
    >;

    "CreatorWithdrew(address,uint256)": TypedContractEvent<
      CreatorWithdrewEvent.InputTuple,
      CreatorWithdrewEvent.OutputTuple,
      CreatorWithdrewEvent.OutputObject
    >;
    CreatorWithdrew: TypedContractEvent<
      CreatorWithdrewEvent.InputTuple,
      CreatorWithdrewEvent.OutputTuple,
      CreatorWithdrewEvent.OutputObject
    >;

    "MonthlyPriceUpdated(uint256,uint256)": TypedContractEvent<
      MonthlyPriceUpdatedEvent.InputTuple,
      MonthlyPriceUpdatedEvent.OutputTuple,
      MonthlyPriceUpdatedEvent.OutputObject
    >;
    MonthlyPriceUpdated: TypedContractEvent<
      MonthlyPriceUpdatedEvent.InputTuple,
      MonthlyPriceUpdatedEvent.OutputTuple,
      MonthlyPriceUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlatformFeeWithdrawn(address,uint256)": TypedContractEvent<
      PlatformFeeWithdrawnEvent.InputTuple,
      PlatformFeeWithdrawnEvent.OutputTuple,
      PlatformFeeWithdrawnEvent.OutputObject
    >;
    PlatformFeeWithdrawn: TypedContractEvent<
      PlatformFeeWithdrawnEvent.InputTuple,
      PlatformFeeWithdrawnEvent.OutputTuple,
      PlatformFeeWithdrawnEvent.OutputObject
    >;

    "Subscribed(address,uint256,uint256,uint256)": TypedContractEvent<
      SubscribedEvent.InputTuple,
      SubscribedEvent.OutputTuple,
      SubscribedEvent.OutputObject
    >;
    Subscribed: TypedContractEvent<
      SubscribedEvent.InputTuple,
      SubscribedEvent.OutputTuple,
      SubscribedEvent.OutputObject
    >;
  };
}
