// ============================================================
// OnlyHold - Mock Data (replace with real blockchain data)
// ============================================================

import { Creator, Content } from './types';

export const MOCK_CREATORS: Creator[] = [
  {
    id: '1',
    address: '0x1234567890abcdef1234567890abcdef12345678',
    name: 'Aria Nakamura',
    username: 'aria_nft',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aria',
    coverImage: 'https://images.unsplash.com/photo-1635322966219-b75ed372eb01?w=1200&auto=format&fit=crop',
    bio: 'Digital artist & NFT creator. Creating exclusive generative art and behind-the-scenes content for true collectors.',
    category: 'art',
    totalSubscribers: 3240,
    totalEarnings: '89,420',
    isVerified: true,
    nftContractAddress: '0xabc123...',
    nftPrice: '0.08',
    stablecoinPrice: '15',
    contentCount: 47,
    joinedAt: '2024-01-15',
    socialLinks: { twitter: 'aria_nft', website: 'arianakamura.art' },
  },
  {
    id: '2',
    address: '0xabcdef1234567890abcdef1234567890abcdef12',
    name: 'DJ Synthesize',
    username: 'dj_synth',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=djsynth',
    coverImage: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=1200&auto=format&fit=crop',
    bio: 'Electronic music producer. Exclusive stems, samples, and studio sessions only for holders.',
    category: 'music',
    totalSubscribers: 1890,
    totalEarnings: '42,100',
    isVerified: true,
    nftContractAddress: '0xdef456...',
    nftPrice: '0.05',
    stablecoinPrice: '10',
    contentCount: 62,
    joinedAt: '2024-03-01',
    socialLinks: { twitter: 'dj_synth', instagram: 'djsynthesize' },
  },
  {
    id: '3',
    address: '0x9876543210fedcba9876543210fedcba98765432',
    name: 'FitChain Luna',
    username: 'fitchain_luna',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=luna',
    coverImage: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1200&auto=format&fit=crop',
    bio: 'Web3 fitness coach. Custom workout plans, nutrition guides & live sessions for NFT holders.',
    category: 'fitness',
    totalSubscribers: 5610,
    totalEarnings: '127,800',
    isVerified: false,
    nftPrice: '0.03',
    stablecoinPrice: '20',
    contentCount: 128,
    joinedAt: '2023-11-20',
    socialLinks: { instagram: 'fitchain_luna' },
  },
  {
    id: '4',
    address: '0xdeadbeef1234567890deadbeef1234567890dead',
    name: 'CryptoShot Marcus',
    username: 'cryptoshot',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=marcus',
    coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&auto=format&fit=crop',
    bio: 'Travel photographer exploring the world, one blockchain at a time. Exclusive raw files and editing tutorials.',
    category: 'photography',
    totalSubscribers: 2150,
    totalEarnings: '56,300',
    isVerified: true,
    nftContractAddress: '0xghi789...',
    nftPrice: '0.06',
    stablecoinPrice: '12',
    contentCount: 89,
    joinedAt: '2024-02-10',
    socialLinks: { instagram: 'cryptoshot', website: 'marcusphoto.xyz' },
  },
  {
    id: '5',
    address: '0xfedcba9876543210fedcba9876543210fedcba98',
    name: 'GG Nexus',
    username: 'gg_nexus',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=nexus',
    coverImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&auto=format&fit=crop',
    bio: 'Pro gamer & streamer. Tournament strategy, exclusive gaming content, and community tournaments for NFT holders.',
    category: 'gaming',
    totalSubscribers: 8920,
    totalEarnings: '203,500',
    isVerified: true,
    nftContractAddress: '0xjkl012...',
    nftPrice: '0.04',
    stablecoinPrice: '8',
    contentCount: 215,
    joinedAt: '2023-09-05',
    socialLinks: { twitter: 'gg_nexus', website: 'nexus.gg' },
  },
  {
    id: '6',
    address: '0x1111222233334444555566667777888899990000',
    name: 'Web3 Sage Priya',
    username: 'web3sage',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya',
    coverImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&auto=format&fit=crop',
    bio: 'DeFi researcher & educator. Deep dives, market analysis, and exclusive research reports for serious learners.',
    category: 'education',
    totalSubscribers: 4300,
    totalEarnings: '98,200',
    isVerified: true,
    nftPrice: '0.10',
    stablecoinPrice: '25',
    contentCount: 76,
    joinedAt: '2024-01-01',
    socialLinks: { twitter: 'web3sage', website: 'web3sage.io' },
  },
];

export const MOCK_CONTENT: Content[] = [
  {
    id: 'c1',
    creatorId: '1',
    creatorName: 'Aria Nakamura',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aria',
    creatorUsername: 'aria_nft',
    title: 'Behind the Brush: Generative Art Process',
    description: 'Exclusive look at how I create my latest collection using custom algorithms and hand-painted textures.',
    type: 'video',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop',
    isExclusive: true,
    requiredTier: 'nft',
    likes: 847,
    comments: 62,
    createdAt: '2025-01-20',
    tags: ['art', 'generative', 'process'],
  },
  {
    id: 'c2',
    creatorId: '2',
    creatorName: 'DJ Synthesize',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=djsynth',
    creatorUsername: 'dj_synth',
    title: 'Exclusive Studio Session - Track #47',
    description: 'Full stem pack from my latest unreleased track. 128 stems, 320kbps WAV files.',
    type: 'audio',
    thumbnail: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600&auto=format&fit=crop',
    isExclusive: true,
    requiredTier: 'stablecoin',
    likes: 512,
    comments: 38,
    createdAt: '2025-01-19',
    tags: ['music', 'stems', 'exclusive'],
  },
  {
    id: 'c3',
    creatorId: '3',
    creatorName: 'FitChain Luna',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=luna',
    creatorUsername: 'fitchain_luna',
    title: 'My free workout announcement',
    description: 'Join me this Saturday for a free live workout stream!',
    type: 'text',
    isExclusive: false,
    likes: 1240,
    comments: 89,
    createdAt: '2025-01-18',
    tags: ['fitness', 'announcement'],
  },
  {
    id: 'c4',
    creatorId: '4',
    creatorName: 'CryptoShot Marcus',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=marcus',
    creatorUsername: 'cryptoshot',
    title: 'Tokyo Neon Nights - RAW Collection',
    description: '50 exclusive RAW files from my Tokyo trip. Includes Lightroom presets.',
    type: 'image',
    thumbnail: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&auto=format&fit=crop',
    isExclusive: true,
    requiredTier: 'nft',
    likes: 2103,
    comments: 147,
    createdAt: '2025-01-17',
    tags: ['photography', 'tokyo', 'raw'],
  },
  {
    id: 'c5',
    creatorId: '5',
    creatorName: 'GG Nexus',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=nexus',
    creatorUsername: 'gg_nexus',
    title: 'Pro Strategy Guide - Season 12',
    description: 'My complete meta guide including champion tier lists, macro strategies, and replay analysis.',
    type: 'text',
    thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop',
    isExclusive: true,
    requiredTier: 'stablecoin',
    likes: 3870,
    comments: 294,
    createdAt: '2025-01-16',
    tags: ['gaming', 'strategy', 'guide'],
  },
  {
    id: 'c6',
    creatorId: '6',
    creatorName: 'Web3 Sage Priya',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya',
    creatorUsername: 'web3sage',
    title: 'DeFi Yield Farming Alpha Report Q1 2025',
    description: 'Exclusive 40-page research report covering the top 20 yield opportunities with risk analysis.',
    type: 'text',
    thumbnail: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&auto=format&fit=crop',
    isExclusive: true,
    requiredTier: 'nft',
    likes: 1560,
    comments: 211,
    createdAt: '2025-01-15',
    tags: ['defi', 'research', 'yield'],
  },
];

export const CATEGORIES = [
  { value: 'all', label: 'All', icon: '🌐' },
  { value: 'art', label: 'Art', icon: '🎨' },
  { value: 'music', label: 'Music', icon: '🎵' },
  { value: 'fitness', label: 'Fitness', icon: '💪' },
  { value: 'gaming', label: 'Gaming', icon: '🎮' },
  { value: 'education', label: 'Education', icon: '📚' },
  { value: 'lifestyle', label: 'Lifestyle', icon: '✨' },
  { value: 'photography', label: 'Photography', icon: '📷' },
  { value: 'writing', label: 'Writing', icon: '✍️' },
];

export const SUPPORTED_CHAINS = {
  mainnet: { id: 1, name: 'Ethereum' },
  polygon: { id: 137, name: 'Polygon' },
  arbitrum: { id: 42161, name: 'Arbitrum' },
  base: { id: 8453, name: 'Base' },
};
