/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mocks from "./mocks";
export { OnlyHoldFactory__factory } from "./OnlyHoldFactory__factory";
export { OnlyHoldNFT__factory } from "./OnlyHoldNFT__factory";
export { OnlyHoldSubscription__factory } from "./OnlyHoldSubscription__factory";
